// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Support"
          title="Common Questions"
          description="Getting started is easy."
          items={[
            {
              question: "What is the turnaround time?",
              answer: "Standard edits are delivered within 48 hours for event packages.",
            },
            {
              question: "Do you offer prints?",
              answer: "Yes, high-end professional prints are available via your private gallery.",
            },
            {
              question: "Are you available for travel?",
              answer: "Absolutely. I travel for editorial projects and destination sessions.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
