// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "gallery" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function GallerySection(): React.JSX.Element {
  return (
    <div id="gallery" data-section="gallery">
        <SectionErrorBoundary name="gallery">
              <FeaturesRevealCardsBento
          tag="Highlights"
          title="Visual Storytelling"
          description="Explore the aesthetic diversity of our studio's creative output."
          items={[
            {
              title: "Texture",
              description: "Detail macro photography",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/young-woman-abstract-photo-shoot_23-2148547003.jpg",
            },
            {
              title: "Branding",
              description: "Product visual identity",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/wet-fresh-beautiful-colorful-feather-textured-background_23-2148114617.jpg",
            },
            {
              title: "Motion",
              description: "Dynamic action shots",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/couple-taking-photos-light-movie-projector_23-2149377354.jpg",
            },
            {
              title: "Portraits",
              description: "Raw human character",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/gorgeous-woman-posing-with-hand-shoulder_23-2148364757.jpg",
            },
            {
              title: "Automotive",
              description: "Metallic luxury detail",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/dynamic-liquid-metal-abstract-background_84443-87053.jpg",
            },
            {
              title: "Weddings",
              description: "Elegant decor events",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/late-april-through-early-may-tulip-fields-netherlands-colourfully-burst-into-full-bloom-fortunately-there-are-hundreds-flower-fields-dotted-dutch-countryside-which_181624-33699.jpg",
            },
            {
              title: "Landscape",
              description: "Cinematic wide angles",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/bearded-elderly-businessman-man-with-mobile-phone-senior-black-suit_1157-46618.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
