// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBrand from '@/components/sections/hero/HeroBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBrand
          brand="DAVONSHOTIT"
          description="Quality Shots. Real Moments. Lasting Memories. Photography and visual content that transforms everyday moments into unforgettable stories."
          primaryButton={{
            text: "Book Your Shoot",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Explore Work",
            href: "#work",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/portrait-beautiful-fashion-stylish-brunette-woman-model-with-evening-makeup-red-lips-white-jacket_158538-11541.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
