/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Check } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";

const photoPlans = [
  {
    tag: "SOLO",
    price: "$70",
    period: "per session",
    description: "Individual portrait or lifestyle shoot.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Solo portrait session", "High-resolution edited photos", "Online gallery delivery"]
  },
  {
    tag: "DUO",
    price: "$70",
    period: "per session",
    description: "Together / No Individuals.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Couple / Duo posing", "High-resolution edited photos", "Online gallery delivery"]
  },
  {
    tag: "DUO INDIVIDUALS",
    price: "$140",
    period: "per session",
    description: "Together photos + individual portraits for both.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Couple & individual shots", "High-resolution edited photos", "Full gallery access"]
  },
  {
    tag: "GROUP (3+)",
    price: "$70",
    period: "per session",
    description: "Group Photos Only.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["3+ people group coverage", "High-resolution edited photos", "Online gallery delivery"]
  },
  {
    tag: "GROUP + INDIVIDUALS",
    price: "$50",
    period: "per person",
    description: "Group photos + individual solo shots for each person.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Group & solo portraits", "Per person pricing", "High-resolution edited photos"]
  },
  {
    tag: "EVENTS",
    price: "$70",
    period: "/ HR",
    description: "Event coverage with online gallery included.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Proms, parties & events", "Hourly event coverage", "Online Gallery Included"]
  }
];

const videoPlans = [
  {
    tag: "SHORT BTS VINTAGE CLIP",
    price: "$15",
    period: "per clip",
    description: "Aesthetic vintage behind-the-scenes video clip.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Raw vintage aesthetic", "Quick social media format", "Fast turnaround"]
  },
  {
    tag: "BTS VINTAGE EDIT",
    price: "$40",
    period: "10–15 Seconds",
    description: "Cinematic edited vintage short-form video.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["10–15 seconds edited video", "Color graded vintage look", "Social media ready"]
  },
  {
    tag: "CAMERAMAN FOR VLOGGING",
    price: "$50",
    period: "/ HR",
    description: "Dedicated videographer coverage for vlogs & events.",
    primaryButton: { text: "Book Your Shoot", href: "#contact" },
    featuresTitle: "Details",
    features: ["Dedicated cameraman", "Hourly videography", "Full video footages"]
  }
];

const plans = [...photoPlans, ...videoPlans];

type PricingPlan = {
  tag: string;
  price: string;
  period: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  featuresTitle: string;
  features: string[];
};

const PricingInline = () => (
  <section aria-label="Pricing section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Investment"}</p>
        </div>

        <TextAnimation
          text={"Custom Packages"}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Premium services for creators and couples."}
          variant={"fade-blur"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
          </div>
        )}
      </div>

      <div className="flex flex-col gap-5 w-content-width mx-auto">
        {plans.map((plan) => (
          <ScrollReveal
            variant="slide-up"
            key={plan.tag}
            className="flex flex-col md:flex-row gap-5 md:gap-12 p-5 md:p-12 card rounded"
          >
            <div className="flex flex-col gap-2 justify-between w-full md:w-1/2">
              <div className="flex flex-col gap-2">
                <div className="px-3 py-1 mb-2 w-fit text-sm card rounded">
                  <p>{plan.tag}</p>
                </div>
                <div className="flex items-baseline gap-1">
                  <span className="text-5xl md:text-6xl font-semibold">{plan.price}</span>
                  <span className="text-2xl font-medium">{plan.period}</span>
                </div>
                <p className="text-xl md:text-2xl leading-snug text-balance">{plan.description}</p>
              </div>

              <div className="flex flex-col gap-3">
                <Button text={plan.primaryButton.text} href={plan.primaryButton.href} variant="primary" className="w-full" />
                {plan.secondaryButton && <Button text={plan.secondaryButton.text} href={plan.secondaryButton.href} variant="secondary" className="w-full" />}
              </div>
            </div>

            <div className="w-full h-px bg-foreground/20 md:hidden" />

            <div className="flex flex-col gap-3 w-full md:w-1/2">
              <h3 className="text-xl font-medium truncate">{plan.featuresTitle}</h3>
              <div className="w-full h-px bg-foreground/5" />
              {plan.features.map((feature) => (
                <div key={feature} className="flex items-start gap-3">
                  <div className="flex items-center justify-center shrink-0 size-6 primary-button rounded">
                    <Check className="size-3 text-primary-cta-text" strokeWidth={2} />
                  </div>
                  <span className="text-base leading-snug">{feature}</span>
                </div>
              ))}
            </div>
          </ScrollReveal>
        ))}
      </div>
    </div>
  </section>
);

export default function PricingSection() {
  return (
    <div data-webild-section="pricing" data-section="pricing" id="pricing">
      <PricingInline />
    </div>
  );
}
