// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialSection(): React.JSX.Element {
  return (
    <div id="social" data-section="social">
        <SectionErrorBoundary name="social">
              <SocialProofMarquee
          tag="Trusted by"
          title="Creative Collaborators"
          description="Working with brands and individuals who value high-end vision."
          names={[
            "VOGUE",
            "HARPER'S",
            "NIKE",
            "ADIDAS",
            "APPLE",
            "SONY",
            "NETFLIX",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
