// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Reviews"
          title="Client Stories"
          description="Hear what our clients have to say about their visual journey."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Creative Lead",
              company: "Vogue",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-women-working-together_23-2150506066.jpg",
            },
            {
              name: "Michael Chen",
              role: "Founder",
              company: "StartupX",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-man-with-bright-smile_23-2148563438.jpg",
            },
            {
              name: "Emily R.",
              role: "Marketing Dir.",
              company: "GrowthCo",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/brunette-girl-wearing-blue-dress-high-heels-sitting-fireplace_132075-12009.jpg",
            },
            {
              name: "David Kim",
              role: "Artist",
              company: "Independent",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-happy-businesswoman-with-notebook-holding-her-diary-planner-sitting-office_1258-194721.jpg",
            },
            {
              name: "Alex P.",
              role: "Event Coordinator",
              company: "GlobalEvents",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/special-product-photography-studio-with-workers_23-2148970220.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
