// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "work" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WorkSection(): React.JSX.Element {
  return (
    <div id="work" data-section="work">
        <SectionErrorBoundary name="work">
              <FeaturesMediaCarousel
          tag="Portfolio"
          title="Selected Works"
          description="A glimpse into the stories we've documented for brands and individuals."
          items={[
            {
              title: "Couple Portraits",
              description: "Authentic chemistry.",
              buttonIcon: "Camera",
              imageSrc: "http://img.b2bpic.net/free-photo/lovely-indian-couple-love-wear-saree-elegant-suit-posed-outdoor-terrace-summer-sunny-day_627829-878.jpg",
            },
            {
              title: "Cinematic BTS",
              description: "Production coverage.",
              buttonIcon: "Film",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-women-enjoying-ice-cream_23-2149428109.jpg",
            },
            {
              title: "Artist Editorial",
              description: "Creative visual identity.",
              buttonIcon: "Mic",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-man-playing-guitar-studio_23-2150232079.jpg",
            },
            {
              title: "Urban Street Fashion",
              description: "Bold visual narratives.",
              buttonIcon: "Zap",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-man-posing-outdoors_23-2150204405.jpg",
            },
            {
              title: "Events & Milestones",
              description: "Captured raw emotion.",
              buttonIcon: "Star",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-woman-reading-magazine_1303-9950.jpg",
            },
            {
              title: "Professional Portraits",
              description: "Your brand amplified.",
              buttonIcon: "User",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-man-suffering-from-schizophrenia_23-2149332544.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
